### ISSUE TITLE
rhvoice build error

### ISSUE THREAD

**Issue by lavrenkov-sketch** [Aculeasis/rhvoice-rest#2]
After install, when try start
python3 rhvoice-rest.py

Warning! Preprocessing disable: No module named 'rhvoice_tools'
Warning! Unsupported library version (API: ('0.7.2', '1.0.0'); LIB: 1.2.0)
Traceback (most recent call last):
  File "rhvoice-rest.py", line 114, in <module>
    tts = TTS()
  File "/usr/local/lib/python3.7/dist-packages/rhvoice_wrapper/rhvoice_wrapper.py", line 489, in __init__
    self._voices = test.voices
  File "/usr/local/lib/python3.7/dist-packages/rhvoice_wrapper/rhvoice_proxy.py", line 303, in voices
    return get_voices(self._lib, self._engine)
  File "/usr/local/lib/python3.7/dist-packages/rhvoice_wrapper/rhvoice_proxy.py", line 269, in get_voices
    country='NaN' if old else vi.country.decode()
AttributeError: 'NoneType' object has no attribute 'decode'

**Comment by Aculeasis** [comment]
This is [rhvoice-wrapper](https://github.com/Aculeasis/rhvoice-proxy) issue, i fixed it in 0.5.2 - `python3 -m pip install -U rhvoice-wrapper`.

Also, you using custom voices? I don't see voices without country flag. Please, execute this code and post result here:
```python
from rhvoice_wrapper import TTS


def test(voices):
    name_len = 5
    voice_order = []
    for v in sorted(voices.items(), key=lambda x: x[1]['no']):
        voice_order.append(v[0])
        if len(v[1]['name']) > name_len:
            name_len = len(v[1]['name'])
    print('Voice {}Language  Gender   Country'.format(' ' * (name_len - 5)))
    line = '  {name:#}  {lang:2}     {gender:6}     {country:2}'.replace('#', str(name_len + 1), 1)
    for i in range(len(voices)):
        voice = voices[voice_order[i]]
        print(line.format(**voice))


tts = TTS(threads=1)
test(tts.voices_info)
tts.join()
```
